image: docker:stable

variables:
  CONTAINER_IMAGE: harbor.zjuqsc.com/mobile-api/intl
  IMAGE_TAG: harbor.zjuqsc.com/mobile-api/intl:$CI_COMMIT_REF_SLUG

before_script:
  - docker login -u docker -p $DOCKER_PASSWORD harbor.zjuqsc.com

build:
  stage: build
  tags:
    - docker
  script:
    - docker pull $IMAGE_TAG || true
    - docker build --cache-from $IMAGE_TAG -t $IMAGE_TAG .
    - docker push $IMAGE_TAG